name: proxy-control-plane

services:
  api:
    container_name: proxy-control-plane_api
    image: proxy-control-plane_api:local
    restart: unless-stopped
    build: .
    env_file:
      - ${PCP_APP_ENV_FILE:-.local/app.env}
    ports:
      - "127.0.0.1:9710:9710"

networks:
  default:
    name: proxy-control-plane_network
